#!/bin/bash

mkdir -p dst

riscv64-elf-gcc \
    -O3 \
    -march=rv32i \
    -mabi=ilp32 \
    -ffreestanding \
    -nostdlib \
    -T link.ld \
    $1 \
    -lgcc \
    -o dst/file.elf

python3 asm.py dst/file.elf out.b
