BLOCKS_IN_KILOBLOCK = 255
MAX_KILOBLOCK_COUNT = 255

BREAKPOINT_EVERY_CYCLE = True
BREAKPOINT_EVERY_INSTRUCTION = False

assert BLOCKS_IN_KILOBLOCK <= 255
assert MAX_KILOBLOCK_COUNT <= 255


SCRAP_COUNT = 16
